apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  labels:
    component: etcd
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
  - name: etcd
    image: registry.k8s.io/etcd:3.5.12-0
    command:
    - etcd
    - --advertise-client-urls=http://HOST_IP:2379
    - --listen-client-urls=http://0.0.0.0:2379
    - --data-dir=/var/lib/etcd
    - --listen-peer-urls=http://0.0.0.0:2380
    - --initial-cluster=default=http://HOST_IP:2380
    - --initial-advertise-peer-urls=http://HOST_IP:2380
    - --initial-cluster-state=new
    - --initial-cluster-token=etcd-cluster
    - --name=default
    volumeMounts:
    - name: etcd-data
      mountPath: /var/lib/etcd
    livenessProbe:
      httpGet:
        path: /health
        port: 2379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
      periodSeconds: 10
      failureThreshold: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  volumes:
  - name: etcd-data
    hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate

